title: "Symonds.dev"
tagline: "Blog"
description: ""
url: https://symonds.dev
baseurl: /

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

author:
  name: "Matthew Symonds"
  github: "symonds"

social:
  github: symonds

google_analytics:
