title:            'Symonds.io'
tagline:          'Blog'
description:      ''
url:              https://www.symonds.io
baseurl:          /

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
paginate:         5

author:
  name:           'Matthew Symonds'
  github:         'symonds'

social:
  github:         symonds
  disqus:         symonds

google_analytics:
